name: app_recetas
description: App de Recetas con Provider y consumo de API
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^0.13.5

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
